import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald, Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${workSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <footer className="border-t border-border bg-white">
          <div className="max-w-5xl mx-auto px-6 md:px-10 py-7 flex flex-col items-center justify-between gap-3">
            <p className="text-sm text-gray-800 letter-spacing-[0.02em] text-align:center font-body">
              I used some prompt engineering with Claude Code to generate the look & feel, along with some CSS and HTML, and I
              reviewed and audited it, focusing on web accessibility, semantic HTML structure, and Tailwind CSS classes. This
              is still an experimental, continuously evolving landing page.
              More info in the <a href="https://github.com/dgattoni/dgattoni.github.io" target="_blank"
                className="text-pink-500 hover:underline">Readme file</a> of my GitHub repository.
            </p>
            <p className="text-sm text-gray-800 letter-spacing-[0.02em] text-align:center mt-5 font-body">
            Daniela Gattoni &mdash; Full-Stack Software Engineer, Melbourne &copy; 2026.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
